services:
  backend:
    build: ./backend
    container_name: homepagescan-backend
    restart: always
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./backend/static:/app/static
    environment:
      - ADMIN_PASSWORD=admin

  frontend:
    build: ./frontend
    container_name: homepagescan-frontend
    restart: always
    ports:
      - "5173:80"
    extra_hosts:
      - "backend:host-gateway"
