services:
  backend:
    build: ./backend
    container_name: homepagescan-backend
    restart: always
    volumes:
      - ./data:/app/data
      - ./backend/static:/app/static
    environment:
      - ADMIN_PASSWORD=admin
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: homepagescan-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
